name: Morning LINE Report

on:
  schedule:
    - cron: "00 07 * * *"
    - cron: "05 07 * * *"
    - cron: "00 23 * * *"
    - cron: "40 20 * * *"
  workflow_dispatch:
jobs:
  run-report:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install packages
        run: pip install -r requirements.txt

      - name: Run morning report
        env:
            TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
            TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
            GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        run: python morning_report.py
